require 'rubygems'
require 'eventmachine'
require 'activesupport'
require 'ostruct'
require 'json'
require 'sinatra'

require File.dirname(__FILE__) + '/mini/listener'
require File.dirname(__FILE__) + '/mini/irc'
require File.dirname(__FILE__) + '/mini/web'