#!/usr/local/bin/ruby

# FIXME: REMOVE
require File.dirname(__FILE__) + '/../lib/mini'
Mini::Bot.commands["echo"] = lambda { |*args| puts args }
# FIXME: REMOVE

command, *args = ARGV
Mini::Bot.run(command, args)